# SPDX-FileCopyrightText: 2013 The freestyle-hid Authors
#
# SPDX-License-Identifier: 0BSD

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=test (ubuntu-latest, 3.7)"
      - "status-success=test (ubuntu-latest, 3.8)"
      - "status-success=test (ubuntu-latest, 3.9)"
      - "status-success=test (macos-latest, 3.7)"
      - "status-success=test (macos-latest, 3.8)"
      - "status-success=test (macos-latest, 3.9)"
      - "status-success=test (windows-latest, 3.7)"
      - "status-success=test (windows-latest, 3.8)"
      - "status-success=test (windows-latest, 3.9)"
      - "status-success=pre-commit"
    actions:
      merge:
        method: rebase
  - name: Automatic merge from Flameeyes
    conditions:
      - "author=Flameeyes"
      - "status-success=test (ubuntu-latest, 3.7)"
      - "status-success=test (ubuntu-latest, 3.8)"
      - "status-success=test (ubuntu-latest, 3.9)"
      - "status-success=test (macos-latest, 3.7)"
      - "status-success=test (macos-latest, 3.8)"
      - "status-success=test (macos-latest, 3.9)"
      - "status-success=test (windows-latest, 3.7)"
      - "status-success=test (windows-latest, 3.8)"
      - "status-success=test (windows-latest, 3.9)"
      - "status-success=pre-commit"
    actions:
      merge:
        method: rebase
